language: c

cache: ccache

sudo: required

addons:
    apt:
        packages:
            - gperf
            - elfutils
            - zlib1g-dev
            - libmemcached-dev
            - libmemcached-tools
            - memcached
            - mingw32
            - mingw32-binutils
            - clang    # scan-build

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

matrix:
    include:
        - os: linux
          compiler: gcc
          sudo: required
          dist: trusty
          env: FEATURES="--enable-memcached"
#        - os: linux
#          compiler: i586-mingw32msvc-gcc
#          env: HOST="--host=i586-mingw32msvc" TEST="test/main.exe"
        - os: linux
          compiler: clang
          env: CFLAGS="-fsanitize=undefined" ASAN_OPTIONS="detect_leaks=0"
        - os: linux
          compiler: clang
          env: CFLAGS="-fsanitize=address -g" ASAN_OPTIONS="detect_leaks=0"
        - os: linux
          compiler: clang
          env: PATH="/usr/bin:$PATH" TEST=analyze
        - os: linux
          compiler: gcc
          env: CUDA=8.0.61-1
        - os: osx
          osx_image: xcode8.2
          compiler: clang
          env: FEATURES="--enable-memcached"
        - os: osx
          osx_image: xcode9
          compiler: clang
          env: FEATURES="--enable-memcached"

    exclude:
        - os: osx
          compiler: gcc

before_install:
    - source ./.travis/install_cuda.sh
    # OSX dependencies
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libmemcached; fi


script:
    - ./autogen.sh
    - ./configure $HOST $FEATURES
    - make
    - make ${TEST:-test}
