language: c

cache: ccache

sudo: required

addons:
    apt:
        packages:
            - asciidoc
            - libxslt1-dev
            - xsltproc
            - docbook-xml
            - docbook-xsl
            - gperf
            - elfutils
            - zlib1g-dev
            - libmemcached-dev
            - libmemcached-tools
            - memcached
            - mingw32
            - mingw32-binutils
            - clang    # scan-build

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

env:
  global:
    - XML_CATALOG_FILES=/usr/local/etc/xml/catalog

matrix:
    include:
        - os: linux
          compiler: gcc
          sudo: required
          dist: trusty
#        - os: linux
#          compiler: i586-mingw32msvc-gcc
#          env: HOST="--host=i586-mingw32msvc" TEST="test/main.exe"
        - os: linux
          compiler: clang
          env: CFLAGS="-fsanitize=undefined" ASAN_OPTIONS="detect_leaks=0"
        - os: linux
          compiler: clang
          env: CFLAGS="-fsanitize=address -g" ASAN_OPTIONS="detect_leaks=0"
        - os: linux
          compiler: clang
          env: PATH="/usr/bin:$PATH" TEST=analyze
        - os: linux
          compiler: gcc
          env: CUDA=8.0.61-1
        - os: osx
          osx_image: xcode8.2
          compiler: clang
        - os: osx
          osx_image: xcode9
          compiler: clang

    exclude:
        - os: osx
          compiler: gcc

before_install:
    - source ./.travis/install_cuda.sh
    # OSX dependencies
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install asciidoc libmemcached; fi


script:
    - ./autogen.sh
    - ./configure --prefix $(pwd)/build $HOST $FEATURES --enable-memcached --with-bundled-zlib
    - make
    - make ${TEST:-test}
    - sudo make install
    - make package


before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; export FILE_TO_UPLOAD="$(pwd)/build/ccache.dmg"; fi

deploy:
  provider: releases
  api_key:
    - secure: G4rIpoLDYsjZhHOptB8pIVvkIinEUAxQpb2EFAwVQHk2tlfVCy0gdDIOdtK22cVAZ/Qj3p8BNeoIOQSHVlkHB9XOH1EGjZK7H/WvOnkjgDigOeoj9vHzg9KvBk8CQB2QSyIkdPy5xg6KfuvgMZW9n/5G/k5Gphl5N5QlDFBTxK6yk9ufBh1RS+wf0czdagUqkAyuMtrBfKx15mKuSFp/TAm+Q9OsCB4gvjHNQnTWCIt87OmtHFKzWpNek4F+UA6zjKd2Veq7yp8KTuAT8qAfOkEMgZjW90Mq/MWgHZ/ZQrez5G40M7sTZz1nNrkeFB40LypQ9wgIUjqrxDQDg2Ns9nDSVhUM4SsNb1uWDWjxiNn6uG/gwXEHt7IttKnzp/pFSON+oXdPdLv3MwPI6z/LWN3v8ncDmVaHysMNKwUGiH7RGefrzd+FhOL3xTxWFnOgZKpBPdMWldHUNPQerh0Fqr/6a5RF8ffhIU3cR672manTlOCW/SLaU+2MvVkB5QxOTlvHCe5v6GUMivTlywDojZW6GelyS+kdZLhL7rsh8kAqxr+3r13Y8rFpsbkz7+VnDaqOSwUkMlMGGrAlbgr8ipFOv74pj8SjpA3d+rlHU5xnA2zU1Eb2uuaGMtSzIdpVlG6akQoRpoqLPM5P4doyOXfm9it3HuKZJabOlulJVOo=
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  overwrite: true
  on:
    tags: false
